apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    foo: bar
  name: test-job
spec:
  template:
    metadata:
      annotations:
        foo: bar
      labels:
        app: test-job
    spec:
      containers:
        - image: gcr.io/cbd-test/test-app:latest
          name: test-app
      restartPolicy: Never
