apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  annotations:
    foo: bar
  name: test-replica-set
spec:
  replicas: 3
  template:
    metadata:
      annotations:
        foo: bar
      labels:
        app: test-replica-set
    spec:
      containers:
        - image: gcr.io/cbd-test/test-app:latest
          name: test-app
