apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-app
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
    app.kubernetes.io/name: my-app
    app.kubernetes.io/version: b2e43cb
  name: test-app
  namespace: foobar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
        app.kubernetes.io/managed-by: gcp-cloud-build-deploy
        app.kubernetes.io/name: my-app
        app.kubernetes.io/version: b2e43cb
    spec:
      containers:
      - image: gcr.io/cbd-test/test-app:latest
        name: test-app


---

apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
  name: foobar
  namespace: foobar
