apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-app
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
  name: test-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
        app.kubernetes.io/managed-by: gcp-cloud-build-deploy
    spec:
      containers:
      - image: gcr.io/cbd-test/test-app:latest
        name: test-app
