apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-app
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
    app.kubernetes.io/name: my-app
    app.kubernetes.io/version: b2e43cb
  name: test-app
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: test-app
  type: LoadBalancer
